dbt_rg_snowflake:
  target: prod
  outputs:
    prod:
      type: snowflake
      account: EOJCPHV-ZQ43317
      database: FD_IO_RG_DLK
      schema: DLK_RG_BDA_ACQUISITION
      # -- Informations sur l'utilisateur et le rôle
      user: ALEXIS.GRAY.EXT
      role: ACCOUNTADMIN

      # -- Configuration de la paire de clés
      private_key_path: /Users/alexis.gray.ext/Projects/credentials/rsa_key.p8
      private_key_passphrase: "valiuz"

      # -- Paramètres de la base de données et de l'entrepôt
      warehouse: RG_SF_WAREHOUSE
      threads: 4
      client_session_keep_alive: False

